/**
 * Generated by Babylon.js Editor
 */

import { dispatchMqttValueToObject, loadScene } from "babylonjs-editor-tools";
import * as scripts_box from "./scripts/box";

export const scriptsMap = {
	"scripts/box.ts": scripts_box,
};

export { dispatchMqttValueToObject, loadScene };
